#pragma once
#include "stm32f4xx.h"

#define STM32F407_MCUCONF

#define STM32_PLLI2S_ENABLED FALSE
#define STM32_SW STM32_SW_PLL
#define STM32_PLLSRC STM32_PLLSRC_HSE
#define STM32_HSE_ENABLED TRUE
#define STM32_HSE_BYPASS FALSE
#define STM32_LSE_ENABLED FALSE
#define STM32_HSI_ENABLED TRUE
#define STM32_LSI_ENABLED TRUE
